### ISSUE TITLE
Feature Request: Add support for docker

### ISSUE THREAD

**Issue by BeatLink** [astashov/liftosaur#158]
Hey guys, 

It would be great if this application could be self hosted via docker

**Comment by marcelmindemann** [comment]
@astashov I am also interested in the idea of self-hosting this. I am wondering if simply running the web frontend according to https://github.com/astashov/liftosaur?tab=readme-ov-file#how-to-run-locally is enough to use Liftosaur at home. Not sure what the mentioned API server running on AWS is about - does the PWA need the API server for any end-user functionality?

**Comment by astashov** [comment]
> I am wondering if simply running the web frontend according to https://github.com/astashov/liftosaur?tab=readme-ov-file#how-to-run-locally is enough to use Liftosaur at home

You won't have any web functionality (web editor, etc), won't have cloud storage - only local storage in a browser. It will **kinda** work, but may miss some functionality here and there.

**Comment by maximbaz** [comment]
I was curious to give it a go, just to see how much work there actually is to selfhost this awesome project - sharing the findings in case someone is also curious to play around 🙂 

Frontend part is very simple, compile the sources and let nginx serve it, nothing special - here's an example `Dockerfile.frontend`:

```Dockerfile
FROM node:18 AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
```

You might want to replace all instances of `https://api3.liftosaur.com` to your own backend (more on that later), and replace `f29180c0746c4922996ff41dfc2527d2` with an empty string or your own Rollbar token (just to be respectful to the author, Rollbar _hopefully_ won't send events from custom domain, but who knows). Also add `exit 0` to the top of `uploadsourcemaps.sh` to disable that integration as well.

To get the backend to work, you need to mock a bunch of AWS services - Lambdas could be replaced with serverless.com (I used v3 to avoid login requirement), dynamodb has an official Docker image `amazon/dynamodb-local`, S3 can be replaced with `minio`.

The following `docker-compose.yml` is a good start (I only omitted the reverse proxy part from it):

```yml
volumes:
  dynamodb:
  minio:

services:
  # used for debugging and initializing dynamodb tables
  aws-cli:
    image: amazon/aws-cli
    entrypoint:
      - tail
      - -f
      - /dev/null
    
  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    volumes:
      - dynamodb:/home/dynamodblocal/data

  minio:
    image: quay.io/minio/minio
    command: server /data
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      IS_LOCAL: "true"
      DYNAMODB_ENDPOINT: http://dynamodb:8000
      S3_ENDPOINT: http://minio:9000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
```

And the corresponding `Dockerfile.backend`:

```Dockerfile
FROM node:18 AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build:lambda

FROM node:18
WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist-lambda ./dist-lambda
COPY --from=builder /app/serverless.yml ./serverless.yml
COPY --from=builder /app/package*.json ./

CMD ["npx", "serverless", "offline", "--host", "0.0.0.0", "--verbose", "--debug", "*"]
```

You'll need this `serverless.yml` file in the root in order to have a persistent container that responds to API calls:

```yaml
service: liftosaur-lambda
frameworkVersion: "3"
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    IS_LOCAL: "true"
    DYNAMODB_ENDPOINT: http://dynamodb:8000
    S3_ENDPOINT: http://minio:9000

functions:
  liftosaurLocal:
    handler: lambda/run.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
      - http:
          path: /
          method: ANY

custom:
  serverless-offline:
    location: dist-lambda
    noPrependStageInUrl: true
    printOutput: true
```

And add these to `devDependencies` in `package.json`:

```json
"serverless": "^3.40.0",
"serverless-offline": "^12.0.4",
```

We can't unfortunately totally avoid patching code, but luckily the patches are really minimal, and perhaps even could be merged if there's a desire to support this use-case.

```patch
   private get dynamo(): DynamoDB.DocumentClient {
     if (this._dynamo == null) {
-      this._dynamo = new DynamoDB.DocumentClient();
+      this._dynamo =
+        process.env.IS_LOCAL !== "true"
+          ? new DynamoDB.DocumentClient()
+          : new DynamoDB.DocumentClient({
+              endpoint: process.env.DYNAMODB_ENDPOINT,
+            });
     }
     return this._dynamo;
   }
```

And exactly the same for S3 (though I didn't end up testing minio).

```patch
   private get s3(): S3 {
     if (this._s3 == null) {
-      this._s3 = new S3();
+      this._s3 =
+        process.env.IS_LOCAL !== "true"
+          ? new S3()
+          : new S3({
+              endpoint: process.env.S3_ENDPOINT,
+            });
     }
     return this._s3;
   }
```

Secrets could be made to be directly read from env vars (e.g. like so), and no AWS mocks are necessary:

```patch
   public async getCookieSecret(): Promise<string> {
-    return this.cache("cookieSecret", () => this.getSecret("cookieSecret"));
+    return process.env.IS_LOCAL === "true"
+      ? process.env.LIFTOSAUR_COOKIE_SECRET
+      : this.cache("cookieSecret", () => this.getSecret("cookieSecret"));
   }

   ...
```

Finally you need to populate the dynamodb tables, as on production this is done via `liftosaur-cdk.ts` but this file doesn't come into play at all on the local environment. There might be a smarter way to do this, I just fed it to ChatGPT and asked it for a corresponding bash script that I could run using `aws-cli` container ( `cat init-dynamodb.sh | docker compose exec -T aws-cli sh` ) - I haven't validated its correctness but that seemed to have worked, but obviously will go out of sync.

```sh
#!/usr/bin/env bash

# Usage:
#   ./init-dynamodb.sh [dev|prod]
# Default is 'prod' (tables get no suffix). If 'dev', suffix is 'Dev'.

set -e

SUFFIX=""
if [ "$1" = "dev" ]; then
  SUFFIX="Dev"
fi

DYNAMODB_ENDPOINT="${DYNAMODB_ENDPOINT:-http://dynamodb:8000}"

echo "Creating DynamoDB tables with suffix='$SUFFIX' at endpoint='$DYNAMODB_ENDPOINT' ..."

aws dynamodb create-table --table-name "lftUsers${SUFFIX}" --attribute-definitions AttributeName=id,AttributeType=S AttributeName=googleId,AttributeType=S AttributeName=appleId,AttributeType=S AttributeName=nickname,AttributeType=S --key-schema AttributeName=id,KeyType=HASH --global-secondary-indexes '[
    {
      "IndexName": "lftUsersGoogleId'${SUFFIX}'",
      "KeySchema": [
        {"AttributeName":"googleId","KeyType":"HASH"}
      ],
      "Projection": {"ProjectionType":"ALL"}
    },
    {
      "IndexName": "lftUsersAppleId'${SUFFIX}'",
      "KeySchema": [
        {"AttributeName":"appleId","KeyType":"HASH"}
      ],
      "Projection": {"ProjectionType":"ALL"}
    },
    {
      "IndexName": "lftUsersNickname'${SUFFIX}'",
      "KeySchema": [
        {"AttributeName":"nickname","KeyType":"HASH"}
      ],
      "Projection": {"ProjectionType":"ALL"}
    }
  ]' --billing-mode PAY_PER_REQUEST --endpoint-url "$DYNAMODB_ENDPOINT" || true

aws dynamodb create-table --table-name "lftAffiliates${SUFFIX}" --attribute-definitions AttributeName=affiliateId,AttributeType=S AttributeName=userId,AttributeType=S --key-schema AttributeName=affiliateId,KeyType=HASH AttributeName=userId,KeyType=RANGE --billing-mode PAY_PER_REQUEST --endpoint-url "$DYNAMODB_ENDPOINT" || true

aws dynamodb create-table --table-name "lftSubscriptionDetails${SUFFIX}" --attribute-definitions AttributeName=userId,AttributeType=S --key-schema AttributeName=userId,KeyType=HASH --billing-mode PAY_PER_REQUEST --endpoint-url "$DYNAMODB_ENDPOINT" || true

aws dynamodb create-table --table-name "lftGoogleAuthKeys${SUFFIX}" --attribute-definitions AttributeName=token,AttributeType=S --key-schema AttributeName=token,KeyType=HASH --billing-mode PAY_PER_REQUEST --endpoint-url "$DYNAMODB_ENDPOINT" || true

aws dynamodb create-table --table-name "lftAppleAuthKeys${SUFFIX}" --attribute-definitions AttributeName=token,AttributeType=S --key-schema AttributeName=token,KeyType=HASH --billing-mode PAY_PER_REQUEST --endpoint-url "$DYNAMODB_ENDPOINT" || true

aws dynamodb create-table --table-name "lftHistoryRecords${SUFFIX}" --attribute-definitions AttributeName=userId,AttributeType=S AttributeName=id,AttributeType=N AttributeName=date,AttributeType=S --key-schema AttributeName=userId,KeyType=HASH AttributeName=id,KeyType=RANGE --global-secondary-indexes '[
    {
      "IndexName": "lftHistoryRecordsDate'${SUFFIX}'",
      "KeySchema": [
        {"AttributeName":"userId","KeyType":"HASH"},
        {"AttributeName":"date","KeyType":"RANGE"}
      ],
      "Projection": {"ProjectionType":"ALL"}
    }
  ]' --billing-mode PAY_PER_REQUEST --endpoint-url "$DYNAMODB_ENDPOINT" || true

aws dynamodb create-table --table-name "lftStats${SUFFIX}" --attribute-definitions AttributeName=userId,AttributeType=S AttributeName=name,AttributeType=S AttributeName=timestamp,AttributeType=N --key-schema AttributeName=userId,KeyType=HASH AttributeName=name,KeyType=RANGE --global-secondary-indexes '[
    {
      "IndexName": "lftStatsTimestamp'${SUFFIX}'",
      "KeySchema": [
        {"AttributeName":"userId","KeyType":"HASH"},
        {"AttributeName":"timestamp","KeyType":"RANGE"}
      ],
      "Projection": {"ProjectionType":"ALL"}
    }
  ]' --billing-mode PAY_PER_REQUEST --endpoint-url "$DYNAMODB_ENDPOINT" || true

aws dynamodb create-table --table-name "lftLogs${SUFFIX}" --attribute-definitions AttributeName=userId,AttributeType=S AttributeName=action,AttributeType=S AttributeName=year,AttributeType=N AttributeName=month,AttributeType=N --key-schema AttributeName=userId,KeyType=HASH AttributeName=action,KeyType=RANGE --global-secondary-indexes '[
    {
      "IndexName": "lftLogsDate'${SUFFIX}'",
      "KeySchema": [
        {"AttributeName":"year","KeyType":"HASH"},
        {"AttributeName":"month","KeyType":"RANGE"}
      ],
      "Projection": {"ProjectionType":"ALL"}
    }
  ]' --billing-mode PAY_PER_REQUEST --endpoint-url "$DYNAMODB_ENDPOINT" || true

aws dynamodb create-table --table-name "lftUserPrograms${SUFFIX}" --attribute-definitions AttributeName=userId,AttributeType=S AttributeName=id,AttributeType=S --key-schema AttributeName=userId,KeyType=HASH AttributeName=id,KeyType=RANGE --billing-mode PAY_PER_REQUEST --endpoint-url "$DYNAMODB_ENDPOINT" || true

aws dynamodb create-table --table-name "lftPrograms${SUFFIX}" --attribute-definitions AttributeName=id,AttributeType=S --key-schema AttributeName=id,KeyType=HASH --billing-mode PAY_PER_REQUEST --endpoint-url "$DYNAMODB_ENDPOINT" || true

aws dynamodb create-table --table-name "lftUrls${SUFFIX}" --attribute-definitions AttributeName=id,AttributeType=S --key-schema AttributeName=id,KeyType=HASH --billing-mode PAY_PER_REQUEST --endpoint-url "$DYNAMODB_ENDPOINT" || true

aws dynamodb create-table --table-name "lftFreeUsers${SUFFIX}" --attribute-definitions AttributeName=id,AttributeType=S --key-schema AttributeName=id,KeyType=HASH --billing-mode PAY_PER_REQUEST --endpoint-url "$DYNAMODB_ENDPOINT" || true

aws dynamodb create-table --table-name "lftCoupons${SUFFIX}" --attribute-definitions AttributeName=code,AttributeType=S --key-schema AttributeName=code,KeyType=HASH --billing-mode PAY_PER_REQUEST --endpoint-url "$DYNAMODB_ENDPOINT" || true

aws dynamodb create-table --table-name "lftDebug${SUFFIX}" --attribute-definitions AttributeName=id,AttributeType=S --key-schema AttributeName=id,KeyType=HASH --billing-mode PAY_PER_REQUEST --endpoint-url "$DYNAMODB_ENDPOINT" || true

aws dynamodb create-table --table-name "lftEvents${SUFFIX}" --attribute-definitions AttributeName=userId,AttributeType=S AttributeName=timestamp,AttributeType=N --key-schema AttributeName=userId,KeyType=HASH AttributeName=timestamp,KeyType=RANGE --billing-mode PAY_PER_REQUEST --endpoint-url "$DYNAMODB_ENDPOINT" || true

echo "Enabling TTL on lftEvents${SUFFIX} for attribute 'ttl'..."
aws dynamodb update-time-to-live --table-name "lftEvents${SUFFIX}" --time-to-live-specification "Enabled=true, AttributeName=ttl" --endpoint-url "$DYNAMODB_ENDPOINT" || true

echo "Done creating local DynamoDB tables."
```

With the above done, the frontend launches (don't forget you need to visit `/app`), the frontend connects to your local backend, everything seems fine on the first glance 😉 

What else?

- User login, as there unfortunately aren't local users, you'd have to create your own Google oauth app and put its details in `src/utils/googleAccessToken.ts`
- S3, I didn't really look much into that. You have no default programs (though I suppose you will import your own anyway), you get no exercise images, probably more stuff is missing. There would need to be found a way to populate `minio` with some content.

At this point I stopped, but it was fun 😁  Hope someone finds this interesting or useful!

Thanks for the awesome project once again!
